services:
  torch-nginx:
    restart: unless-stopped
    image: nginxinc/nginx-unprivileged:1.30-alpine
  environment:
    FHIR_SERVER_HOSTNAME: ${FHIR_SERVER_HOSTNAME:-fhir.localhost}
    KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME:-auth.localhost}
    FLARE_HOSTNAME: ${FLARE_HOSTNAME:-flare.localhost}
    TORCH_HOSTNAME: ${TORCH_HOSTNAME:-torch.localhost}
    TERMINOLOGY_SERVER_HOSTNAME: ${TERMINOLOGY_SERVER_HOSTNAME:-terminology.localhost}
    FHIR_PSEUDONYMIZER_HOSTNAME: ${FHIR_PSEUDONYMIZER_HOSTNAME:-dimp.localhost}
    FHIR_FLATTENER_HOSTNAME: ${FHIR_FLATTENER_HOSTNAME:-flattener.localhost}
    FHIR_VALIDATOR_HOSTNAME: ${FHIR_VALIDATOR_HOSTNAME:-validator.localhost}
  ports:
    - ${TORCH_PORT:-127.0.0.1:8086}:8080
  env_file:
    - .env
  volumes:
    - "${TORCH_DATA_VOLUME:-triangle-torch-data-store}:/app/output"
    - ../auth:/app/certs
  extra_hosts:
    - "auth.localhost:host-gateway"

volumes:
  triangle-torch-data-store:
